# Generated by Django 3.2.11 on 2022-02-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120, unique=True)),
                ('author', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField(default=50)),
                ('copies', models.PositiveIntegerField(default=50)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
    ]
