# Generated by Django 3.2.11 on 2022-02-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
