# Generated by Django 3.2.11 on 2022-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_expected_delivert_date_orders_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
