# Generated by Django 3.2.11 on 2022-03-02 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0004_orders_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=250)),
                ('profile_pic', models.ImageField(upload_to='image')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
